NODE_ENV: development
SITE_URL: http://0.0.0.0:5000/

# Mongodb
MONGOLAB_URI: mongodb://heroku_app15646528:1lni7ufv8ul956f6mm12sm7v7h@ds033297.mongolab.com:33297/heroku_app15646528

# Redis
REDISCLOUD_URL: redis://rediscloud:HDyM7ZwKK9hueLzG@pub-redis-15042.us-east-1-2.2.ec2.garantiadata.com:15042

# Facebook
FACEBOOK_APP_ID: 126152087583067
FACEBOOK_APP_SECRET: 832631de611cf2bc813fa3d3ebfaf201